### ISSUE TITLE
CRUD for Users

### ISSUE THREAD

**Issue by amymariewall** [amymariewall/02-29-pair-project#12]
- Create
- [x] Sign up form
- Read
- [x] View Individual User page
- [x] View ALL users page (optional?)
- Update
- [x] Form to update name, email, password, or bio
- [x] Link to this form on View Individual User page
- Delete
- [x] Button on View Individual User page to delete that user

**Comment by halfghaninne** [comment]
Each CRUD set can be broken up into separate issues. 

It _may_ also be helpful to list the controller actions associated with each of these views, though not necessary.

**Comment by halfghaninne** [comment]
Also, please account for dependencies. Does deleting a user delete their updates for example? Investments in them / investments they've made?

A separate Issue may be one of authorization. Who can delete a User?
